/*
class Person{
  final String name;
  final int age;

  const Person({required this.name, required this.age});

  @override
  String toString() {
    return 'Person{name of person: $name, age: $age}';
  }
}*/

import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'person.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'person.g.dart';

@freezed
abstract class Person with _$Person {
  const factory Person({required String name, required int age}) = _Person;

  factory Person.fromJson(Map<String, Object?> json) => _$PersonFromJson(json);
}
